MagicMatch Offerset plugin
aurora-scheduler/aurora pull request #80
Opened 2020-10-13 15:52 UTC by lenhattan86

### Description:
The plugin sends the request and offer list to a plugin running on the same node with aurora.
It receives the response (sorted offers) from the plugin, and proceeds the task assignment process.

### Testing Done:
- Performance & Scalability tests
- Failover test.
- Plugin failure test.

2020-10-14 23:37 UTC, ridv reviewed
Make sure to format the Java code in the same style as the rest of the project.

2020-10-14 23:37 UTC, ridv commented on src/main/java/com/paypal/aurora/scheduler/offers/OfferSetModule.java
> +    LOG.info("PayPal Offer Set module Enabled.");
Maybe we can rename it to MagicMatch OfferSet Module instead.

2020-10-15 16:05 UTC, zorro786 requested changes

2020-10-15 16:05 UTC, zorro786 commented on src/main/java/com/paypal/aurora/scheduler/offers/OfferSetImpl.java
> +      BufferedReader br = new BufferedReader(new InputStreamReader(con.getInputStream(), "utf-8"));
Use `IOUtils.toString(con.getInputStream())`, avoid boiler plate code.

2020-10-15 16:12 UTC, zorro786 commented on src/main/java/com/paypal/aurora/scheduler/offers/OfferSetModule.java
> +    LOG.info("PayPal Offer Set module Enabled.");
Also can you create a new File and not replace the default one?

2020-10-15 16:13 UTC, zorro786 commented on src/main/java/com/paypal/aurora/scheduler/offers/OfferSetModule.java
> +    LOG.info("PayPal Offer Set module Enabled.");
Also I meant renaming of the file 'OfferSetModule` to 'MagicMatchOfferSetModule`, not just the log on line 30.

2020-10-15 16:29 UTC, zorro786 commented on src/main/java/com/paypal/aurora/scheduler/offers/PluginConfig.java
> +      targetFile = new FileInputStream(new File(this.configFile));
You can directly use `FileUtils.readFileToString`

2020-10-15 17:20 UTC, ridv commented on src/main/java/com/paypal/aurora/scheduler/offers/OfferSetModule.java
> +        bind(OfferSet.class).to(OfferSetImpl.class);
I'm not well versed on binding with Guice so I'll defer to your judgement on this.

2020-10-15 17:25 UTC, lenhattan86 commented on src/main/java/com/paypal/aurora/scheduler/offers/OfferSetImpl.java
> +	  for (HostOffer offer:offers) {
fixed it. will push.

2020-10-15 17:26 UTC, lenhattan86 commented on src/main/java/com/paypal/aurora/scheduler/offers/OfferSetImpl.java
> +    LOG.error("MagicMatch failed to schedule the task. Aurora uses the default scheduler.");
fixed it. will push.

2020-10-15 17:30 UTC, lenhattan86 commented on src/main/java/com/paypal/aurora/scheduler/offers/OfferSetModule.java
> +    LOG.info("PayPal Offer Set module Enabled.");
fixed the LOG but will check if Plugin still works with the new name.

2020-10-15 17:32 UTC, lenhattan86 commented on src/main/java/com/paypal/aurora/scheduler/offers/OfferSetImpl.java
> +          LOG.error("Cannot find this host "+host+" in "+offerMap.size()+" offers");
fixed. will push.

2020-10-15 17:40 UTC, lenhattan86 commented on src/main/java/com/paypal/aurora/scheduler/offers/OfferSetImpl.java
> +    Gson gson = new Gson();
fixed it. will push.

2020-10-15 17:43 UTC, lenhattan86 commented on src/main/java/com/paypal/aurora/scheduler/offers/PluginConfig.java
> +    FileInputStream targetFile = null;
good catch. Fixed. will push.

2020-10-15 17:44 UTC, lenhattan86 commented on src/main/java/com/paypal/aurora/scheduler/offers/PluginConfig.java
> +public class PluginConfig {
I already changed the classes -> inner classes instead. will push.

2020-10-15 17:44 UTC, lenhattan86 commented on src/main/java/com/paypal/aurora/scheduler/offers/PluginConfig.java
> +      LOG.error(io.toString());
fixed. will push.

2020-10-15 18:07 UTC, zorro786 commented on src/main/java/com/paypal/aurora/scheduler/offers/OfferSetModule.java
> +    LOG.info("PayPal Offer Set module Enabled.");
Injection works on interface for this module, whatever actual implementation you bind doesn't depend on class name.

2020-10-15 18:14 UTC, zorro786 commented on src/main/java/com/paypal/aurora/scheduler/offers/OfferSetModule.java
> +        bind(OfferSet.class).to(OfferSetImpl.class);
`bind(OfferSet.class).to(OfferSetImpl.class).asEagerSingleton()` (I prefer) or ` bind(OfferSet.class).to(OfferSetImpl.class).in(Singleton.class)`

2020-10-15 20:51 UTC, lenhattan86 commented on src/main/java/com/paypal/aurora/scheduler/offers/OfferSetImpl.java
> +      LOG.error(ioe.toString());
fixed. will push.

2020-10-15 20:53 UTC, lenhattan86 commented on src/main/java/com/paypal/aurora/scheduler/offers/OfferSetImpl.java
> +      BufferedReader br = new BufferedReader(new InputStreamReader(con.getInputStream(), "utf-8"));
The method `IOUtils.toString` is deprecated.

2020-10-15 20:56 UTC, lenhattan86 commented on src/main/java/com/paypal/aurora/scheduler/offers/OfferSetModule.java
> +  public OfferSetModule(CliOptions options) {
yes. I followed the native class from org.apache.aurora.scheduler.offers.OfferManagerModule

2020-10-15 20:57 UTC, lenhattan86 commented on src/main/java/com/paypal/aurora/scheduler/offers/OfferSetModule.java
> +        bind(OfferSet.class).to(OfferSetImpl.class);
why do we need these changes when the native one works fine.
`org.apache.aurora.scheduler.offers.OfferManagerModule`

2020-10-15 21:01 UTC, lenhattan86 commented on src/main/java/com/paypal/aurora/scheduler/offers/PluginConfig.java
> +      targetFile = new FileInputStream(new File(this.configFile));
good point. Fixed. will push

2020-10-15 21:16 UTC, ridv commented on src/main/java/com/paypal/aurora/scheduler/offers/OfferSetModule.java
> +        bind(OfferSet.class).to(OfferSetImpl.class);
Just more streamlined, if it doesn't hurt I say let's do it 😄

2020-10-15 21:16 UTC, ridv commented on src/main/java/com/paypal/aurora/scheduler/offers/PluginConfig.java
> +      jsonStr = IOUtils.toString(targetFile, "UTF-8");
What encoding does this fall back on if we don't specify?

2020-10-15 21:17 UTC, zorro786 commented on src/main/java/com/paypal/aurora/scheduler/offers/OfferSetImpl.java
> +      BufferedReader br = new BufferedReader(new InputStreamReader(con.getInputStream(), "utf-8"));
There must be a replacement right? They would have changed arguments or something...

2020-10-15 21:21 UTC, zorro786 commented on src/main/java/com/paypal/aurora/scheduler/offers/OfferSetModule.java
> +        bind(OfferSet.class).to(OfferSetImpl.class);
For me two reasons:
1. Java code is quite verbose and chaining is a good way to utilize that feature.
2. Two calls to `bind()` are avoided.

This is a nit for me so up to you.

2020-10-15 21:23 UTC, zorro786 commented on src/main/java/com/paypal/aurora/scheduler/offers/OfferSetImpl.java
> +      BufferedReader br = new BufferedReader(new InputStreamReader(con.getInputStream(), "utf-8"));
Check their Java Docs to find alternatives...

2020-10-15 21:23 UTC, lenhattan86 commented on src/main/java/com/paypal/aurora/scheduler/offers/OfferSetModule.java
> +        bind(OfferSet.class).to(OfferSetImpl.class);
Great. Will double check & fix it.

2020-10-15 21:29 UTC, zorro786 commented on src/main/java/com/paypal/aurora/scheduler/offers/OfferSetModule.java
> +  public OfferSetModule(CliOptions options) {
What's the relation between that class and this w.r.t. `public` visibility?

2020-10-15 21:30 UTC, zorro786 commented on src/main/java/com/paypal/aurora/scheduler/offers/OfferSetModule.java
> +  public OfferSetModule(CliOptions options) {
Are you talking about 
```
  public static class OfferSetModule extends AbstractModule {
    private final CliOptions options;

    public OfferSetModule(CliOptions options) {
      this.options = options;
    }

    @Override
    protected void configure() {
      install(new PrivateModule() {
        @Override
        protected void configure() {
          bind(new TypeLiteral<Ordering<HostOffer>>() { })
              .toInstance(OfferOrderBuilder.create(options.offer.offerOrder));
          bind(OfferSetImpl.class).in(Singleton.class);
          bind(OfferSet.class).to(OfferSetImpl.class);
          expose(OfferSet.class);
        }
      });
    }
  }
```
this class?

2020-10-15 21:33 UTC, zorro786 commented on src/main/java/com/paypal/aurora/scheduler/offers/OfferSetModule.java
> +  public OfferSetModule(CliOptions options) {
Hmm I feel `public` is not needed for constructor even here from what I see - this class is initialised by its parent class and not used anywhere else. But since I don't have more info here it is safe to follow native code I guess.

2020-10-15 23:22 UTC, mauri commented
Is this PR on the right repo? why is the package com.paypal.aurora?

2020-10-16 16:44 UTC, ridv commented
Hey @mauri, glad to see you're still around 😄 . We'll probably change the packaging name but we're upstreaming an offer sorting module that's able to use an external program with a defined interface to sort offers. The reason this is an HTTP interface is because we wanted to be able to use a program written in a different language to do this (we wrote ours in Go).

We *may* maintain this sorter in a different repo but we figured we'd try to upstream it first.

2020-10-17 22:40 UTC, lenhattan86 commented on src/main/java/com/paypal/aurora/scheduler/offers/OfferSetImpl.java
> +      BufferedReader br = new BufferedReader(new InputStreamReader(con.getInputStream(), "utf-8"));
fixed it. will push.

2020-10-17 22:45 UTC, lenhattan86 commented on src/main/java/com/paypal/aurora/scheduler/offers/PluginConfig.java
> +      jsonStr = IOUtils.toString(targetFile, "UTF-8");
If we don't specify UTF-8, it depends on OS, and mostly its not recommended.
I searched across aurora code, UTF-8 is used a lot too.

2020-10-20 16:11 UTC, ridv reviewed
Can we migrate the package from `src/main/java/com/paypal/aurora...` to `src/main/java/io/github/aurora-scheduler/...`?

Also we could use some documentation for the HTTP endpoints MagicMatch uses. That way someone else can come in and replace MagicMatch with something of their own.

In fact, we could rename this OfferSet module to be called something like `HttpOfferSet` at this point. @zorro786 and @lenhattan86 any thoughts?

2020-10-20 16:21 UTC, lenhattan86 commented on src/main/java/com/paypal/aurora/scheduler/offers/PluginConfig.java
> +    final String  configFile = "/etc/magicmatch/aurora-plugin.json";
Sure, will change.

2020-10-20 16:23 UTC, lenhattan86 commented on src/main/java/com/paypal/aurora/scheduler/offers/PluginConfig.java
> +    final String  configFile = "/etc/magicmatch/aurora-plugin.json";
We can either move to src/main/java/io/github/aurora-scheduler/... or just create a new repo in aurora-scheduler.

2020-10-22 22:20 UTC, lenhattan86 commented
@ridv @zorro786 Can you guys take another pass?

2020-10-22 23:56 UTC, zorro786 requested changes

2020-10-22 23:56 UTC, zorro786 commented on src/main/java/io/github/aurora/scheduler/offers/HttpOfferSetImpl.java
> +      //numOfTasks,currTotalSchedTime,currWorstSchedTime,totalSchedTime,worstSchedTime
This comment is redundant.

2020-10-22 23:56 UTC, zorro786 commented on src/main/java/io/github/aurora/scheduler/offers/HttpOfferSetImpl.java
> +      LOG.info(msg);
I would send the metrics to `/vars` similar to how other native metrics are sent. That way you don't have to enable debug logs to see the metrics and you can see them always. Also printing these in logs for normal scheduler run is not a good pattern.

2020-10-22 23:56 UTC, zorro786 commented on src/main/java/io/github/aurora/scheduler/offers/HttpPluginConfig.java
> +  public boolean isDebug() {
This should be runtime enabled config, if you are trying to log. Use `org.slf4j.Logger` methods to see if debug is enabled at log level to print this. Service shouldn't be restarted to enable/disable debug mode.

2020-10-22 23:56 UTC, zorro786 commented on src/main/java/io/github/aurora/scheduler/offers/HttpPluginConfig.java
> +  private String endpoint = "http://localhost:9090";
this can be `static final`

2020-10-22 23:56 UTC, zorro786 commented on src/main/java/io/github/aurora/scheduler/offers/HttpPluginConfig.java
> +    final String configFile = "/etc/aurora-scheduler/http-endpoint.json";
this can be class variable.

2020-10-22 23:56 UTC, zorro786 commented on src/main/java/io/github/aurora/scheduler/offers/HttpPluginConfig.java
> +    } catch (IOException io) {
What are you doing with exceptions here after catching? If there is no config file how can the plugin run? You should throw an exception and let the caller know if you don't have a default config.

2020-10-22 23:56 UTC, zorro786 commented on src/main/java/io/github/aurora/scheduler/offers/HttpOfferSetImpl.java
> +      hosts[i] = new Host();
Can you create a constructor for Host class and pass name and offer together?

2020-10-22 23:56 UTC, zorro786 commented on src/main/java/io/github/aurora/scheduler/offers/HttpOfferSetImpl.java
> +      LOG.error("The HTTP protocol was not setup correctly. \n" + pe.toString());
You shouldn't convert exception to string, it is anti slf4j pattern. Neither do you need a new line character. Instead do
`LOG.error("The HTTP protocol was not setup correctly", pe)`
Here and elsewhere in exceptions.

2020-10-22 23:56 UTC, zorro786 commented on src/main/java/io/github/aurora/scheduler/offers/HttpOfferSetImpl.java
> +public class HttpOfferSetImpl implements OfferSet {
Why not name it MagicMatchOfferSetImpl? HttpOfferSet is not making an implementation sense.

2020-10-22 23:56 UTC, zorro786 commented on src/main/java/io/github/aurora/scheduler/offers/HttpOfferSetImpl.java
> + * Implementation for OfferSet.
What kind of implementation? It's a class that implements OfferSet so we know it's an implementation.

2020-10-22 23:56 UTC, zorro786 commented on src/main/java/io/github/aurora/scheduler/offers/HttpOfferSetImpl.java
> +      return null;
Why don't you return empty list `orderedOffers` instead and check for empty list instead of null? Avoid returning nulls if possible.

2020-10-22 23:56 UTC, zorro786 commented on src/main/java/io/github/aurora/scheduler/offers/HttpOfferSetImpl.java
> +      con = (HttpURLConnection) url.openConnection();
What is the client timeout configured for this connection?

2020-10-22 23:56 UTC, zorro786 commented on src/main/java/io/github/aurora/scheduler/offers/HttpOfferSetImpl.java
> +    } catch (IOException ioe) {
How are you handling RuntimeException here and below?

2020-10-22 23:56 UTC, zorro786 commented on src/main/java/io/github/aurora/scheduler/offers/HttpOfferSetImpl.java
> +@VisibleForTesting
Please add some tests for your code. UTs at the minimum.

2020-10-22 23:56 UTC, zorro786 commented on src/main/java/io/github/aurora/scheduler/offers/HttpOfferSetImpl.java
> +      int c = 0;
Could you name this variable better?

2020-10-22 23:56 UTC, zorro786 commented on src/main/java/io/github/aurora/scheduler/offers/HttpOfferSetImpl.java
> +    String[] hosts;
Use ArrayList<String> instead. Prefer lists over arrays whenever possible.

2020-10-22 23:56 UTC, zorro786 commented on src/main/java/io/github/aurora/scheduler/offers/HttpOfferSetImpl.java
> +    if (scheduleResponse.error.equals("") && scheduleResponse.hosts != null) {
What if error is null?. Also you shouldn't create a new `StringBuffer()` object below if len(hosts) == 0

2020-10-23 05:50 UTC, mauri commented on src/main/java/io/github/aurora/scheduler/offers/HttpOfferSetImpl.java
> +    try (OutputStream os = con.getOutputStream()) {
Please use a higher level abstraction such as [Apache HttpClient](http://hc.apache.org/httpcomponents-client-ga/quickstart.html) to do the request instead of implementing it using low level java.net API. It will make the code simpler and rely on an already proven implementation.

2020-10-23 05:50 UTC, mauri commented on src/main/java/io/github/aurora/scheduler/offers/HttpOfferSetImpl.java
> +      LOG.error("ScheduleRequest json is not valid.\n" + uee.toString());
This exception have nothing to do with json. Using an abstraction such as Apache HttpClient would allow you to not worry about handling this superfluous exception that is unlikely to happen.

2020-10-23 05:50 UTC, mauri commented on src/main/java/io/github/aurora/scheduler/offers/HttpOfferSetImpl.java
> +      String responseLine = IOUtils.toString(con.getInputStream(), StandardCharsets.UTF_8);
This assumes all the plugins needs to reply with UTF-8? Using a library such as HttpClient for this will allow you to not care about this and gracefully handle the response encoding

2020-10-23 05:50 UTC, mauri commented on src/main/java/io/github/aurora/scheduler/offers/HttpOfferSetImpl.java
> +      con = (HttpURLConnection) url.openConnection();
+1 This is potentially blocking the scheduler execution which is very bad. A clear SLA should be defined for how slow the matcher can be.

It needs to timeout not only if the connection is not established but also if the response takes more than certain time to be completed

2020-10-23 05:50 UTC, mauri commented on src/main/java/io/github/aurora/scheduler/offers/HttpOfferSetImpl.java
> +      }
All the "logging logic" is a bit distracting from the core of this method, consider something like this to improve readability:

```Log.info("Sorted offers: " + String.join(",", scheduleResponse.hosts.subList(0, Math.min(5,scheduleResponse.hosts.length)) + "...")```

In that way, when reading the code, you see the line is about logging right away, and you can skip it if not interested.

2020-10-23 05:50 UTC, mauri commented on src/main/java/io/github/aurora/scheduler/offers/HttpOfferSetImpl.java
> +    return null;
What about turning this logic around? first check if `Strings.isEmptyOrNull(error)` and return null right away if it's set. Then let the flow continue with the happy path.

BTW for API clarity, I'd argue that we shouldn't check the content of the error string. If error is !null then regardless of the content, it's an error.

2020-10-23 15:53 UTC, lenhattan86 commented on src/main/java/io/github/aurora/scheduler/offers/HttpOfferSetImpl.java
> +      //numOfTasks,currTotalSchedTime,currWorstSchedTime,totalSchedTime,worstSchedTime
will fix.

2020-10-23 15:57 UTC, lenhattan86 commented on src/main/java/io/github/aurora/scheduler/offers/HttpPluginConfig.java
> +  private String endpoint = "http://localhost:9090";
I make it configurable so it should not static final.

2020-10-23 16:00 UTC, lenhattan86 commented on src/main/java/io/github/aurora/scheduler/offers/HttpOfferSetImpl.java
> +    } catch (IOException ioe) {
It is already handled. It returns null so the plugin can fall back to the native scheduler.

2020-10-23 16:06 UTC, lenhattan86 commented on src/main/java/io/github/aurora/scheduler/offers/HttpOfferSetImpl.java
> +@VisibleForTesting
In this project, we only can do unit tests for public methods. However we have only 1 public method that needs http connection for testing.

2020-10-23 16:08 UTC, lenhattan86 commented on src/main/java/io/github/aurora/scheduler/offers/HttpOfferSetImpl.java
> +    String[] hosts;
This is for gson to parse from json to object.

2020-10-23 19:00 UTC, zorro786 commented on src/main/java/io/github/aurora/scheduler/offers/HttpOfferSetImpl.java
> +    } catch (IOException ioe) {
I mistook "openConnection" to actually open a network connection. My comment is more valid for below in `getOutputStream` or `getInputStream`. You are not handling RuntimeExceptions here, https://docs.oracle.com/javase/8/docs/api/java/lang/RuntimeException.html
For network connections there is a possibility of RuntimeExceptions, so it is better to catch them too and handle accordingly, especially if the caller is not handling them.

2020-10-23 19:01 UTC, zorro786 commented on src/main/java/io/github/aurora/scheduler/offers/HttpOfferSetImpl.java
> +      LOG.error("ScheduleRequest json is not valid.\n" + uee.toString());
I believe the above exception extends IOException, you can combine both below in IOException catch block to reduce superfluousness as pointed out by @mauri., if you choose to stick with native client.

2020-10-23 20:17 UTC, lenhattan86 commented on src/main/java/io/github/aurora/scheduler/offers/HttpOfferSetImpl.java
> +      LOG.error(e.toString());
good point, will fix.

2020-10-23 20:17 UTC, lenhattan86 commented on src/main/java/io/github/aurora/scheduler/offers/HttpPluginConfig.java
> +public class HttpPluginConfig {
yes, will do.

2020-10-23 21:48 UTC, zorro786 commented on src/main/java/io/github/aurora/scheduler/offers/HttpOfferSetImpl.java
> +public class HttpOfferSetImpl implements OfferSet {
To clarify what I mean above, the current default one is also an "HttpOfferSet" as offers are sent over HTTP to/from Aurora.

2020-10-23 22:17 UTC, zorro786 commented on src/main/java/io/github/aurora/scheduler/offers/HttpOfferSetImpl.java
> +    String[] hosts;
Hmm not sure I follow, are you saying we can not convert JSON string to ScheduleResponse object if we use a List<String> ?

2020-10-26 18:28 UTC, ridv reviewed
Really good job @lenhattan86 this PR has come a long way from the initial version.

2020-10-26 18:28 UTC, ridv commented on src/main/java/io/github/aurora/scheduler/offers/HttpOfferSetImpl.java
> +public class HttpOfferSetImpl implements OfferSet {
The reason I asked for this to be renamed to HttpOfferSet is because this will be a generic interface for anyone who wants to implement their own offer sorter outside of Aurora. Currently there is no way to make that happen. This de-couples MagicMatch itself fro the interface which it uses to communicate with Aurora.

2020-10-26 18:28 UTC, ridv commented on src/main/java/io/github/aurora/scheduler/offers/HttpPluginConfig.java
> +    } catch (IOException io) {
Two choices here:

1. Fail the scheduler.
2. Throw a warning message saying the plugin is not configured properly.

Aurora has traditionally erred on the side of failing the scheduler to warn users about misconfiguration.

2020-10-26 20:42 UTC, zorro786 commented on src/main/java/io/github/aurora/scheduler/offers/HttpOfferSetImpl.java
> +public class HttpOfferSetImpl implements OfferSet {
`HttpOfferSetImpl` is a class not an interface right?, not sure if I got your point. Did you mean to say other `offer sorter` classes will extend this class?

2020-10-26 21:17 UTC, ridv commented on src/main/java/io/github/aurora/scheduler/offers/HttpOfferSetImpl.java
> +public class HttpOfferSetImpl implements OfferSet {
Oh sorry, it's not meant to be an interface in the Java sense. I meant it as an HTTP Interface to the outside world so that anyone can implement the interface externally and create a sorter in another language.

I can see how that can get confusing though. Maybe we can rename it `ExternalOfferSetImpl`? Would that be less confusing?

2020-10-26 21:36 UTC, lenhattan86 commented on src/main/java/io/github/aurora/scheduler/offers/HttpOfferSetImpl.java
> +public class HttpOfferSetImpl implements OfferSet {
I prefer HttpOfferSet. We cannot expect a short name that can explain everything. 
External is too general. Http works better this case. While the default uses the name "OfferSet", I think adding Http gives readers enough info.

2020-10-26 21:38 UTC, lenhattan86 commented on src/main/java/io/github/aurora/scheduler/offers/HttpOfferSetImpl.java
> +      LOG.error("ScheduleRequest json is not valid.\n" + uee.toString());
good point, fixed.

2020-11-05 19:54 UTC, lenhattan86 commented on src/main/java/com/paypal/aurora/scheduler/model/Config.java
> +package com.paypal.aurora.scheduler.model;
we agreed to have another the package name.

2020-12-01 23:01 UTC, lenhattan86 commented on src/main/java/io/github/aurora/scheduler/offers/HttpOfferSetImpl.java
> +      LOG.info(msg);
Thanks for the comment. I already made the change to push these variables to `/vars.`

2020-12-01 23:02 UTC, lenhattan86 commented on src/main/java/io/github/aurora/scheduler/offers/HttpPluginConfig.java
> +  public boolean isDebug() {
we no longer need it.

2020-12-01 23:03 UTC, lenhattan86 commented on src/main/java/io/github/aurora/scheduler/offers/HttpPluginConfig.java
> +    final String configFile = "/etc/aurora-scheduler/http-endpoint.json";
we don't need configFile any more.

2020-12-01 23:03 UTC, lenhattan86 commented on src/main/java/io/github/aurora/scheduler/offers/HttpPluginConfig.java
> +    } catch (IOException io) {
we don't need config file any more.

2020-12-01 23:03 UTC, lenhattan86 commented on src/main/java/io/github/aurora/scheduler/offers/HttpOfferSetImpl.java
> +      LOG.error("The HTTP protocol was not setup correctly. \n" + pe.toString());
fixed and pushed.

2020-12-01 23:09 UTC, lenhattan86 commented on src/main/java/io/github/aurora/scheduler/offers/HttpOfferSetImpl.java
> + * Implementation for OfferSet.
I added the docs for this. pushed.

2020-12-01 23:10 UTC, lenhattan86 commented on src/main/java/io/github/aurora/scheduler/offers/HttpOfferSetImpl.java
> +      con = (HttpURLConnection) url.openConnection();
I added configurable timeout for this.

2020-12-01 23:10 UTC, lenhattan86 commented on src/main/java/io/github/aurora/scheduler/offers/HttpOfferSetImpl.java
> +      int c = 0;
it was removed.

2020-12-01 23:20 UTC, lenhattan86 commented on src/main/java/io/github/aurora/scheduler/offers/HttpOfferSetImpl.java
> +    if (scheduleResponse.error.equals("") && scheduleResponse.hosts != null) {
good point. fixed & pushed.

2020-12-01 23:21 UTC, lenhattan86 commented on src/main/java/io/github/aurora/scheduler/offers/HttpOfferSetImpl.java
> +    Host[] hosts;
thanks. Fixed & pushed.

2020-12-01 23:22 UTC, lenhattan86 commented on src/main/java/io/github/aurora/scheduler/offers/HttpOfferSetImpl.java
> +          + Arrays.toString(hosts) + '}';
this was removed.

2020-12-01 23:25 UTC, lenhattan86 commented on src/main/java/io/github/aurora/scheduler/offers/HttpOfferSetImpl.java
> +      return null;
this was removed.

2020-12-01 23:28 UTC, lenhattan86 commented on src/main/java/io/github/aurora/scheduler/offers/HttpOfferSetImpl.java
> +      hosts[i] = new Host();
good point. Fixed & pushed.

2020-12-05 05:11 UTC, ridv requested changes
Let's switch to using the Apache HTTP client and I think we're ready to ship!

2020-12-05 05:11 UTC, ridv commented on src/main/java/io/github/aurora/scheduler/offers/HttpOfferSetImpl.java
> +    try (OutputStream os = con.getOutputStream()) {
@lenhattan86 let's address this. I think Mauricio's advice here is sage and it'll lower the amount of lines of code we use here. It'll also give us better performance in most cases it looks like: https://stackoverflow.com/questions/18570206/how-do-jersey-client-and-apache-http-client-compare

2020-12-16 01:29 UTC, lenhattan86 commented on src/main/java/io/github/aurora/scheduler/offers/HttpOfferSetImpl.java
> +    gson = new Gson();
The processing time is too small compared to the scheduling time. 
I found some other files already use gson, so I think its fine for now.
I will work on that if we really need more improvement.

2020-12-16 01:31 UTC, lenhattan86 commented on src/main/java/com/paypal/aurora/scheduler/offers/OfferSetImpl.java
> +  private List<HostOffer> getOffersFromPlugin(ResourceRequest resourceRequest, Iterable<HostOffer> offers){
We don't use config file anymore.

2020-12-16 01:31 UTC, lenhattan86 commented on src/main/java/com/paypal/aurora/scheduler/offers/OfferSetImpl.java
> +      LOG.error(e.toString());
fixed.

2020-12-16 01:32 UTC, lenhattan86 commented on src/main/java/com/paypal/aurora/scheduler/offers/PluginConfig.java
> +      jsonStr = IOUtils.toString(targetFile, "UTF-8");
we don't need to read the config file anymore.

2020-12-16 04:50 UTC, lenhattan86 commented on src/main/java/io/github/aurora/scheduler/offers/HttpOfferSetImpl.java
> +    for (HostOffer offer : offers) {
good point. fixed.

2020-12-16 04:51 UTC, lenhattan86 commented on src/main/java/io/github/aurora/scheduler/offers/HttpOfferSetImpl.java
> +      }
this line is outdated.

2020-12-16 04:51 UTC, lenhattan86 commented on src/main/java/io/github/aurora/scheduler/offers/HttpOfferSetImpl.java
> +    return null;
it was removed.

2020-12-16 04:52 UTC, lenhattan86 commented on src/main/java/io/github/aurora/scheduler/offers/HttpOfferSetImpl.java
> +    gson = new Gson();
great.

2020-12-23 01:45 UTC, lenhattan86 commented on src/main/java/io/github/aurora/scheduler/offers/HttpOfferSetImpl.java
> +      String responseLine = IOUtils.toString(con.getInputStream(), StandardCharsets.UTF_8);
good point. fixed & pushed.

2020-12-23 01:45 UTC, lenhattan86 commented on src/main/java/io/github/aurora/scheduler/offers/HttpOfferSetImpl.java
> +    try (OutputStream os = con.getOutputStream()) {
thanks. fixed & pushed.

2020-12-23 18:34 UTC, ridv approved these changes
:shipit:  Great job @lenhattan86

2020-12-23 19:56 UTC, zorro786 requested changes
Once you fix these, LGTM.

2020-12-23 19:56 UTC, zorro786 commented on src/main/java/io/github/aurora/scheduler/offers/HttpOfferSetImpl.java
> +      LOG.info("Sending request " + scheduleRequest.jobKey);
I think this and below "received response" can be moved to debug, it will fill the logs too much.

2020-12-23 19:56 UTC, zorro786 commented on src/main/java/io/github/aurora/scheduler/offers/HttpOfferSetImpl.java
> +      LOG.info("Response: " + responseStr);
This should be error?

2020-12-23 19:56 UTC, zorro786 commented on src/main/java/io/github/aurora/scheduler/offers/HttpOfferSetImpl.java
> +    offers = new HashSet<>();
You are using a hash set here and a concurrent skip list in constructor below. Can you make them same? If not what is the reason?

2020-12-23 19:56 UTC, zorro786 commented on src/main/java/io/github/aurora/scheduler/offers/HttpOfferSetModule.java
> +      // Ignored. VM shutdown is required to stop computing.
That means you want to shutdown your executor. This function is provided to cleanup.

2020-12-25 04:41 UTC, lenhattan86 commented on src/main/java/io/github/aurora/scheduler/offers/HttpOfferSetImpl.java
> +      LOG.info("Sending request " + scheduleRequest.jobKey);
fixed. will push.

2020-12-25 04:41 UTC, lenhattan86 commented on src/main/java/io/github/aurora/scheduler/offers/HttpOfferSetImpl.java
> +      LOG.info("Response: " + responseStr);
fixed. will push.

2020-12-25 04:49 UTC, lenhattan86 commented on src/main/java/io/github/aurora/scheduler/offers/HttpOfferSetImpl.java
> +    offers = new HashSet<>();
good point. fixed. will push.

2020-12-25 04:53 UTC, lenhattan86 commented on src/main/java/io/github/aurora/scheduler/offers/HttpOfferSetModule.java
> +      // Ignored. VM shutdown is required to stop computing.
Modified the comment to avoid this confusion. I ignored implementing this function like `slaModule.java`

2020-12-25 15:11 UTC, zorro786 commented on src/main/java/io/github/aurora/scheduler/offers/HttpOfferSetImpl.java
>        LOG.info("received response for " + scheduleRequest.jobKey);
This one too.

2020-12-25 15:11 UTC, zorro786 approved these changes
LGTM

2020-12-26 03:27 UTC, lenhattan86 commented on src/main/java/io/github/aurora/scheduler/offers/HttpOfferSetImpl.java
>        LOG.info("received response for " + scheduleRequest.jobKey);
fixed.

2020-12-27 04:50 UTC, merged